language: java

sudo: false

jdk:
  - oraclejdk8
  
before_install:
  - pip install --user codecov
  - wget -O codacy-coverage-reporter.jar "http://search.maven.org/remotecontent?filepath=com/codacy/codacy-coverage-reporter/1.0.4/codacy-coverage-reporter-1.0.4-assembly.jar"

after_success:
  - codecov
  - java -jar codacy-coverage-reporter.jar -l Java -r coverage.xml

branches:
  only:
    - master

notifications:
  email:
    - james@baconi.co.uk
