language: java

sudo: false

jdk:
  - oraclejdk8
  
before_install:
  - pip install --user codecov
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >t.jar
  - java -jar t.jar init
  - rm t.jar
  - jpm install com.codacy:codacy-coverage-reporter:assembly

after_success:
  - codecov
  - codacy-coverage-reporter -l Java -r coverage.xml

branches:
  only:
    - master

notifications:
  email:
    - james@baconi.co.uk
