language: java

sudo: false

jdk:
  - oraclejdk8
  
before_install:
  - pip install --user codecov

after_success:
  - codecov

branches:
  only:
    - master

notifications:
  email:
    - james@baconi.co.uk
